<?php
/**
 * Products
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Products API
 *
 * This is Product API for product data management
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Products model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Products 
{
        /**
     * @var string|null
     * @SerializedName("name")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $name;

    /**
     * @var string|null
     * @SerializedName("category")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $category;

    /**
     * @var string|null
     * @SerializedName("peremp_Date")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $perempDate;

    /**
     * @var string|null
     * @SerializedName("user_Id")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $userId;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->name = isset($data['name']) ? $data['name'] : null;
        $this->category = isset($data['category']) ? $data['category'] : null;
        $this->perempDate = isset($data['perempDate']) ? $data['perempDate'] : null;
        $this->userId = isset($data['userId']) ? $data['userId'] : null;
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name
     *
     * @return $this
     */
    public function setName($name = null)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets category.
     *
     * @return string|null
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Sets category.
     *
     * @param string|null $category
     *
     * @return $this
     */
    public function setCategory($category = null)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Gets perempDate.
     *
     * @return string|null
     */
    public function getPerempDate()
    {
        return $this->perempDate;
    }

    /**
     * Sets perempDate.
     *
     * @param string|null $perempDate
     *
     * @return $this
     */
    public function setPerempDate($perempDate = null)
    {
        $this->perempDate = $perempDate;

        return $this;
    }

    /**
     * Gets userId.
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Sets userId.
     *
     * @param string|null $userId
     *
     * @return $this
     */
    public function setUserId($userId = null)
    {
        $this->userId = $userId;

        return $this;
    }
}


